/* client functions auto-generated by pidl */

#include "includes.h"
#include <tevent.h>
#include "lib/util/tevent_ntstatus.h"
#include "autoconf/librpc/gen_ndr/ndr_leases_db.h"
#include "autoconf/librpc/gen_ndr/ndr_leases_db_c.h"

/* leases_db - client functions generated by pidl */

