/* client functions auto-generated by pidl */

#include "includes.h"
#include <tevent.h>
#include "lib/util/tevent_ntstatus.h"
#include "librpc/gen_ndr/ndr_bkupblobs.h"
#include "librpc/gen_ndr/ndr_bkupblobs_c.h"

/* bkup - client functions generated by pidl */

