/*
 * Unix SMB/CIFS implementation.
 * server auto-generated by pidl. DO NOT MODIFY!
 */

#include "includes.h"
#include "ntdomain.h"
#include "autoconf/librpc/gen_ndr/srv_secrets.h"


/* Tables */
static const struct api_struct api_secrets_cmds[] = 
{
};

const struct api_struct *secrets_get_pipe_fns(int *n_fns)
{
	*n_fns = sizeof(api_secrets_cmds) / sizeof(struct api_struct);
	return api_secrets_cmds;
}

NTSTATUS rpc_secrets_init(const struct rpc_srv_callbacks *rpc_srv_cb)
{
	return rpc_srv_register(SMB_RPC_INTERFACE_VERSION, "secrets", "secrets", &ndr_table_secrets, api_secrets_cmds, sizeof(api_secrets_cmds) / sizeof(struct api_struct), rpc_srv_cb);
}

NTSTATUS rpc_secrets_shutdown(void)
{
	return rpc_srv_unregister(&ndr_table_secrets);
}
