/*
 * Unix SMB/CIFS implementation.
 * server auto-generated by pidl. DO NOT MODIFY!
 */

#include "includes.h"
#include "ntdomain.h"
#include "autoconf/librpc/gen_ndr/srv_libnet_join.h"


/* Tables */
static const struct api_struct api_libnetjoin_cmds[] = 
{
};

const struct api_struct *libnetjoin_get_pipe_fns(int *n_fns)
{
	*n_fns = sizeof(api_libnetjoin_cmds) / sizeof(struct api_struct);
	return api_libnetjoin_cmds;
}

NTSTATUS rpc_libnetjoin_init(const struct rpc_srv_callbacks *rpc_srv_cb)
{
	return rpc_srv_register(SMB_RPC_INTERFACE_VERSION, "libnetjoin", "libnetjoin", &ndr_table_libnetjoin, api_libnetjoin_cmds, sizeof(api_libnetjoin_cmds) / sizeof(struct api_struct), rpc_srv_cb);
}

NTSTATUS rpc_libnetjoin_shutdown(void)
{
	return rpc_srv_unregister(&ndr_table_libnetjoin);
}
